# https://github.com/account/applications/
github_development:
    client_id: b42c51a7552a5d1a0018
    secret: 809828011c8a381eedc2900bf624a93dce542d0d
github_production:
    client_id: 0d4231ea05827ae4e413
    secret: 18d61c80b3d4e206549b54da5d33d386ea158c67

# http://dev.twitter.com/apps
twitter_development:
    consumer_key: 2V0xrY1ZSXqfjOovcyB7Q
    consumer_secret: moWdmQpbVmOTziybHba9FuR4dS7UYT1Wtxa5FYblzaY
twitter_production:
    consumer_key: 2V0xrY1ZSXqfjOovcyB7Q
    consumer_secret: moWdmQpbVmOTziybHba9FuR4dS7UYT1Wtxa5FYblzaY
